name: uuidv6
description: UUID Version 6 for Dart
version: 1.0.0+1
homepage: https://github.com/DizoftTeam/uuidv6

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
